Repository msgphp/msgphp, pull requests merged in 2018-10, with the labels that each got.

#216 use Null coalescing operator
  src/User/Infra/Security/SecurityUser.php
Labels: cs / sa

#217 revise doctrine object mappings
  src/Domain/Infra/DependencyInjection/BundleHelper.php
  src/Domain/Infra/DependencyInjection/Compiler/DoctrineObjectFieldMappingPass.php
  src/Domain/Infra/DependencyInjection/Compiler/ResolveDomainPass.php
  src/Domain/Infra/Doctrine/Event/ObjectMappingListener.php
  src/Domain/Infra/Doctrine/ObjectMappingProviderInterface.php
  src/Domain/Infra/Doctrine/ObjectMappings.php
  src/Domain/Tests/Infra/Doctrine/ObjectMappingsTest.php
  src/Eav/Infra/Doctrine/ObjectMappings.php
  src/Eav/Tests/Infra/Doctrine/ObjectMappingsTest.php
  src/EavBundle/Resources/config/doctrine.php
  src/User/Infra/Doctrine/ObjectMappings.php
  src/User/Tests/Infra/Doctrine/ObjectMappingsTest.php
  src/UserBundle/Resources/config/doctrine.php
Labels: infrastructure

#218 Turn DomainCollection's filter & slice functions into lazy functions
  src/Domain/DomainCollection.php
  src/Domain/Tests/DomainCollectionTest.php
Labels: base domain

#220 Use strict array comparison
  src/Domain/DomainCollection.php
Labels: base domain, cs / sa

#221 update to phpstan-shim
  bin/sa
  composer.json
  phpstan.neon
Labels: cs / sa

#222 update to php-cs-fixer.phar
  .php_cs.dist
  bin/cs
  bin/sami
  composer.json
Labels: cs / sa

#223 revise collection api
  docs/ddd/collections.md
  src/Domain/DomainCollection.php
  src/Domain/Exception/EmptyCollectionException.php
  src/Domain/Exception/UnknownCollectionElementException.php
  src/Domain/Infra/Doctrine/DomainCollection.php
  src/Domain/Infra/InMemory/DomainEntityRepositoryTrait.php
  src/Domain/Tests/AbstractDomainCollectionTest.php
  src/Domain/Tests/DomainCollectionTest.php
Labels: base domain

#224 forward call to doctrine's Collection::getIterator()
  src/Domain/Infra/Doctrine/DomainCollection.php
Labels: infrastructure
